name: circtis_dev
channels:
  - conda-forge
dependencies:
  - shogun=6.1.3
  - libgfortran4=7.5.0
  - scikit-learn=0.24.2
  - pandas=1.1.5
  - biopython=1.79
  - lxml=4.6.3
  - ipykernel=5.5.5
  - seaborn=0.11.2
  - imbalanced-learn=0.7.0
  - pip=21.3.1
  - pip:
    - liftover==1.1.16
